### ISSUE TITLE
Uninstall seems to leave the browser layer behind

### ISSUE THREAD

**Issue by hvelarde** [collective/collective.portlet.calendar#11]
See: https://github.com/plonegovbr/brasil.gov.agenda/issues/137

**Comment by idgserpro** [comment]
This issue is invalid. Uninstall correctly removes the browserlayer. To test it, create a minimalplone installation, install this package, go to http://localhost:8080/Plone/manage_components. You can see

```
  <utility name="CalendarEx" factory="zope.interface.interface.InterfaceClass"
     id="ICalendarExLayer"
     interface="plone.browserlayer.interfaces.ILocalBrowserLayerType"/>
```

Go to `portal_quickinstaller` again, and uninstall the package. Going to http://localhost:8080/Plone/manage_components you can see that is removed.

The problem you had is explained in https://github.com/plonegovbr/brasil.gov.agenda/issues/108#issuecomment-398360701 (link in portuguese).
